# Generated by Django 4.1.5 on 2023-02-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="language",
            field=models.ManyToManyField(to="tutorial.language"),
        ),
    ]
