# Generated by Django 4.1.7 on 2023-02-24 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorial", "0002_tutorial_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="people",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
